import { pipeline } from '@xenova/transformers';
import { UMAP } from 'umap-js';

const sentences = [
	"I don't have any dietary restrictions.",
	'I can eat anything.',
	'I am not allergic to any food.',
	'No dietary restrictions for me.',
	'I have no food restrictions.',
	'I am not on any specific diet.',
	'I can consume all types of food.',
	'My diet is not restricted.',
	'No food limitations for me.',
	'I have no dietary restrictions or allergies.',
	"I don't follow any special dietary requirements.",
	'There are no dietary restrictions for me.',
	"I don't have any food allergies.",
	'I can eat whatever I want.',
	'No dietary limitations for me.',
	'I am not restricted in my diet.',
	"I don't have any specific food requirements.",
	'I am not restricted in what I can eat.',
	"I don't have any food sensitivities.",
	'I have no dietary allergies or restrictions.',
	'I have no restrictions when it comes to food.',
	'There are no dietary restrictions that apply to me.',
	"I don't have any food intolerances.",
	'I am not limited in my diet.',
	"I don't have any dietary preferences or restrictions.",
	'No dietary restrictions or allergies for me.',
	"I don't have any dietary limitations.",
	"I don't have any special dietary needs.",
	'I can eat anything without restrictions.',
	'I am not restricted by any dietary requirements.',
	"I don't have any dietary restrictions or limitations.",
	'I am not allergic to any type of food.',
	"I don't have any dietary restrictions or sensitivities.",
	'I am not limited in what I can eat.',
	"I don't have any specific dietary requirements.",
	'I can eat all kinds of food.',
	"I don't have any food allergies or intolerances.",
	'I am not on a restricted diet.',
	"I don't have any restrictions when it comes to food.",
	'I am not restricted by any dietary restrictions.',
	"I don't follow any strict dietary guidelines.",
	'There are no dietary limitations for me.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not restricted by any food sensitivities.',
	"I don't have any specific dietary allergies.",
	'I am not limited by any food restrictions.',
	'I can eat anything without any dietary limitations.',
	'I am not on any special diet.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any restrictions when it comes to what I can eat.",
	'I am not restricted by any specific dietary requirements.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any particular dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any strict dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	"I don't have any dietary guidelines or restrictions.",
	'I am not restricted by any food allergies.',
	"I don't have any dietary limitations or allergies.",
	"I don't follow any particular dietary rules.",
	'I am not limited by any dietary restrictions.',
	"I don't have any specific dietary needs or restrictions.",
	"I don't have any food limitations or sensitivities.",
	'I am not on any restricted diet plan.',
	"I don't have any dietary restrictions or guidelines.",
	'I am not limited by any food sensitivities or allergies.',
	"I don't have any specific dietary allergies or intolerances.",
	'I am not restricted by any food guidelines.',
	"I don't have any restrictions when it comes to my diet.",
	'I am not on any special dietary plan.',
	"I don't have any dietary restrictions or preferences.",
	"I don't have any limitations when it comes to what I can eat.",
	'I am not restricted by any specific dietary guidelines.',
	"I don't have any food sensitivities or allergies.",
	"I don't follow any strict dietary restrictions.",
	'I am not limited in what I can eat.',
	'I have no specific dietary restrictions or requirements.',
	'I am allergic to dairy products.',
	'I follow a gluten-free diet.',
	'I cannot eat shellfish due to allergies.',
	'I am a vegetarian and do not eat meat or fish.',
	'I am lactose intolerant and avoid all dairy products.',
	'I have a nut allergy and cannot consume any nuts or nut products.',
	'I have celiac disease and need to avoid all gluten-containing foods.',
	'I am allergic to eggs and cannot eat anything containing eggs.',
	'I avoid soy products due to allergies.',
	'I follow a low-carb diet and do not eat starchy foods.',
	'I have a seafood allergy and cannot eat any type of seafood.',
	'I am a vegan and do not consume any animal products.',
	'I am on a no-sugar diet and do not eat anything with added sugars.',
	'I cannot eat spicy foods due to a medical condition.',
	'I have a garlic allergy and need to avoid all dishes containing garlic.',
	'I am on a low-cholesterol diet and avoid high-fat foods.',
	'I am allergic to all types of berries and need to avoid them.',
	'I am on a low-sodium diet and need to avoid salty foods.',
	'I follow a paleo diet and do not eat grains or legumes.',
	'I have a caffeine sensitivity and need to avoid all caffeinated products.',
	'I am allergic to shellfish and cannot consume any type of shellfish.',
	'I am on a diabetic diet and need to watch my sugar intake.',
	'I have a tomato allergy and need to avoid all tomato-based dishes.',
	'I have a pineapple allergy and need to avoid all pineapple products.',
	'I follow a kosher diet and do not eat non-kosher foods.',
	'I am on a low-fat diet and avoid high-fat foods.',
	'I have a sesame seed allergy and need to avoid all sesame products.',
	'I am on a vegan diet and do not consume any animal products.',
	'I cannot eat spicy foods due to a medical condition.',
	'I have a garlic allergy and need to avoid all dishes containing garlic.',
	'I am on a low-cholesterol diet and avoid high-fat foods.',
	'I am allergic to all types of berries and need to avoid them.',
	'I am on a low-sodium diet and need to avoid salty foods.',
	'I follow a paleo diet and do not eat grains or legumes.',
	'I have a caffeine sensitivity and need to avoid all caffeinated products.',
	'I am allergic to shellfish and cannot consume any type of shellfish.',
	'I am on a diabetic diet and need to watch my sugar intake.',
	'I have a tomato allergy and need to avoid all tomato-based dishes.',
	'I have a pineapple allergy and need to avoid all pineapple products.',
	'I follow a kosher diet and do not eat non-kosher foods.',
	'I am on a low-fat diet and avoid high-fat foods.',
	'I have a sesame seed allergy and need to avoid all sesame products.',
	'I am on a vegan diet and do not consume any animal products.',
	'I cannot eat spicy foods due to a medical condition.',
	'I have a garlic allergy and need to avoid all dishes containing garlic.',
	'I am on a low-cholesterol diet and avoid high-fat foods.',
	'I am allergic to all types of berries and need to avoid them.',
	'I am on a low-sodium diet and need to avoid salty foods.',
	'I follow a paleo diet and do not eat grains or legumes.',
	'I have a caffeine sensitivity and need to avoid all caffeinated products.',
	'I am allergic to shellfish and cannot consume any type of shellfish.',
	'I am on a diabetic diet and need to watch my sugar intake.',
	'I have a tomato allergy and need to avoid all tomato-based dishes.',
	'I have a pineapple allergy and need to avoid all pineapple products.',
	'I follow a kosher diet and do not eat non-kosher foods.',
	'I am on a low-fat diet and avoid high-fat foods.',
	'I have a sesame seed allergy and need to avoid all sesame products.',
	'I am allergic to shellfish.',
	'I am lactose intolerant.',
	'I follow a gluten-free diet.',
	'I am vegetarian.',
	'I am vegan.',
	"I don't eat pork.",
	"I don't eat red meat.",
	'I am on a low-carb diet.',
	'I have a nut allergy.',
	'I am allergic to eggs.',
	"I don't eat spicy food.",
	'I have celiac disease.',
	"I can't eat onions.",
	'I am on a keto diet.',
	'I have diabetes.',
	'I am allergic to soy.',
	"I don't eat seafood.",
	"I don't eat dairy.",
	'I am on a paleo diet.',
	'I have a garlic allergy.',
	"I can't eat high cholesterol foods.",
	'I am allergic to peanuts.',
	"I don't eat processed foods.",
	"I don't eat nightshade vegetables.",
	'I have a citrus allergy.',
	'I am on a low-sodium diet.',
	"I can't eat spicy food.",
	"I don't eat grains.",
	"I don't eat beans.",
	'I am allergic to tree nuts.',
	"I don't eat sugar.",
	"I don't eat fast food.",
	"I don't eat fried food.",
	"I can't drink alcohol.",
	"I don't eat high-fat foods.",
	'I am on a low-calorie diet.',
	'I only eat organic food.',
	'I am allergic to sesame seeds.',
	'I have a fruit allergy.',
	"I don't eat processed meats.",
	"I don't eat white flour.",
	"I can't eat spicy food.",
	"I don't eat canned food.",
	'I have a shellfish allergy.',
	"I don't eat eggs.",
	"I can't eat dairy.",
	'I am on a soy-free diet.',
	'I have a caffeine sensitivity.',
	"I don't eat red meat.",
	'I am on a salt-free diet.',
	'I am allergic to mustard.',
	"I don't eat high-cholesterol foods.",
	"I don't eat acidic foods.",
	'I am on a low-cholesterol diet.',
	'I have a wheat allergy.',
	"I don't eat processed sugars.",
	'I am allergic to bell peppers.',
	"I don't eat artificial sweeteners.",
	"I can't eat high-carb foods.",
	'I have a quinoa allergy.',
	"I don't eat processed grains.",
	"I don't eat dairy.",
	'I am on a casein-free diet.',
	'I have an oat allergy.',
	'I am on a caffeine-free diet.',
	"I can't eat fat.",
	"I don't eat junk food.",
	"I don't eat processed oils.",
	"I don't eat canned vegetables.",
	"I don't eat white rice.",
	'I am on a low-sugar diet.',
	'I have a sugar sensitivity.',
	"I don't eat artificial flavors.",
	"I can't eat energy bars.",
	'I am allergic to honey.',
	"I don't eat processed meats.",
	"I don't eat frozen foods.",
	"I don't eat raw fish.",
	"I don't eat high-sodium foods.",
	'I am on a low-fat diet.',
	'I have a vinegar allergy.',
	"I don't eat high-fiber foods.",
	"I don't eat high-fructose corn syrup.",
	'I am on a low-cholesterol diet.',
	'I have a pasta allergy.',
	"I don't eat processed cheese.",
	"I don't eat artificial colors.",
	"I can't eat MSG.",
	"I don't eat white bread.",
	"I don't eat fast food.",
	"I don't eat processed sugars.",
	"I can't eat high-carb foods.",
	'I am on a low-glycemic diet.',
	'I have a rice allergy.',
	"I don't eat frozen meals.",
	"I don't eat raw vegetables.",
	"I don't eat high-sugar foods.",
	'I am on a low-cholesterol diet.',
	'I have a pesto allergy.',
	"I don't eat high-fructose corn syrup.",
	"I don't eat processed snacks.",
	"I can't eat artificial sweeteners.",
	"I don't eat white rice.",
	"I don't eat processed pasta.",
	'I am on a low-sugar diet.',
	"I can't eat high-calorie foods.",
	'I have an aspartame allergy.',
	"I don't eat frozen desserts.",
	"I don't eat dried fruits.",
	"I don't eat high-fat foods.",
	'I am on a low-carb diet.',
	'I have a snack allergy.',
	"I don't eat high-sodium foods.",
	"I don't eat high-cholesterol foods.",
	'I am on a low-calorie diet.',
	"I don't eat processed condiments.",
	"I don't eat white pasta.",
	"I can't eat artificial flavors.",
	"I don't eat fast food.",
	'I am allergic to molasses.',
	"I don't eat processed bread.",
	"I don't eat high-sugar foods.",
	"I don't eat artificial sweeteners.",
	'I am on a low-glycemic diet.',
	'I have a white flour allergy.',
	"I don't eat processed desserts.",
	"I don't eat high-calorie foods.",
	"I can't eat energy bars.",
	"I don't eat fruit snacks.",
	"I don't eat raw fruits.",
	'I am on a low-fat diet.',
	'I have a celery allergy.',
	"I don't eat high-fiber foods.",
	"I don't eat high-fructose corn syrup.",
	'I am on a low-glycemic diet.',
	'I have a corn allergy.',
	"I don't eat frozen vegetables.",
	"I don't eat processed soups.",
	"I can't eat MSG.",
	"I don't eat processed pastries.",
	"I don't eat white bread.",
	"I don't eat processed cereals.",
	'I am on a low-sugar diet.',
	"I can't eat high-carb foods.",
	'I have a chocolate allergy.',
	"I don't eat frozen dinners.",
	"I don't eat canned fruits.",
	"I don't eat high-sugar foods.",
	'I am on a low-cholesterol diet.',
	'I have a barbecue sauce allergy.',
	"I don't eat high-calorie foods.",
	"I don't eat white flour.",
	"I don't eat artificial flavors.",
	'I am on a low-glycemic diet.',
	"I don't eat processed snacks.",
	"I don't eat high-fat foods.",
	"I don't eat high-sodium foods.",
	'I am on a low-fat diet.',
	"I don't eat processed condiments.",
	'I have a ketchup allergy.',
	"I don't eat high-cholesterol foods.",
	"I can't eat artificial sweeteners.",
	"I don't eat high-sugar foods.",
	'I am on a low-sugar diet.',
	"I don't eat processed desserts.",
	'I have a white flour allergy.',
	"I don't eat processed bread.",
	"I don't eat high-calorie foods.",
	'I am allergic to molasses.',
	'I am on a low-glycemic diet.',
	"I don't eat artificial flavors.",
	"I don't eat white bread.",
	"I can't eat energy bars.",
	"I don't eat fruit snacks.",
	"I don't eat high-fiber foods.",
	'I have a celery allergy.',
	'I am on a low-fat diet.',
	"I don't eat high-fructose corn syrup.",
	"I don't eat frozen vegetables.",
	"I don't eat processed soups.",
	'I am on a low-glycemic diet.',
	"I don't eat white bread.",
	'I have a white flour allergy.',
	"I don't eat processed cereals.",
	"I can't eat high-carb foods.",
	'I am on a low-sugar diet.',
	'I have a chocolate allergy.',
	"I don't eat frozen dinners.",
	"I don't eat canned fruits.",
	"I don't eat high-sugar foods.",
	'I am on a low-cholesterol diet.',
	'I have a barbecue sauce allergy.',
	"I don't eat high-calorie foods.",
	"I don't eat white flour.",
	"I don't eat artificial flavors.",
	'I am on a low-glycemic diet.',
	"I don't eat processed snacks.",
	"I don't eat high-fat foods.",
	"I don't eat high-sodium foods.",
	"I don't eat processed condiments.",
	'I am on a low-fat diet.',
	'I have a ketchup allergy.',
	"I don't eat high-cholesterol foods.",
	"I can't eat artificial sweeteners.",
	"I don't eat high-sugar foods.",
	'I am on a low-sugar diet.',
	'I have a white flour allergy.',
	"I don't eat processed desserts.",
	"I don't eat processed bread.",
	"I don't eat high-calorie foods.",
	'I am allergic to molasses.',
	"I don't eat white bread.",
	'I am on a low-glycemic diet.',
	"I don't eat artificial flavors.",
	"I don't eat fruit snacks.",
	"I don't eat high-fiber foods.",
	'I have a celery allergy.',
	"I don't eat high-fructose corn syrup.",
	'I am on a low-fat diet.',
	"I don't eat frozen vegetables.",
	"I don't eat processed soups.",
	'I am on a low-glycemic diet.',
	"I don't eat processed cereals.",
	"I don't eat white bread.",
	"I don't eat high-sugar foods.",
	"I can't eat energy bars.",
	'I am on a low-sugar diet.',
	'I have a chocolate allergy.',
	"I don't eat frozen dinners.",
	"I don't eat canned fruits.",
	"I don't eat high-sugar foods.",
	'I am on a low-cholesterol diet.',
	'I have a barbecue sauce allergy.',
	"I don't eat high-calorie foods.",
	"I don't eat white flour.",
	"I don't eat artificial flavors.",
	'I am on a low-glycemic diet.',
	"I don't eat processed snacks.",
	"I don't eat high-fat foods.",
	"I don't eat high-sodium foods.",
	'I am on a low-fat diet.',
	'I have a ketchup allergy.',
	"I don't eat processed condiments.",
	"I don't eat high-cholesterol foods.",
	"I can't eat artificial sweeteners.",
	"I don't eat high-sugar foods.",
	'I am on a low-sugar diet.',
	'I have a white flour allergy.',
	"I don't eat processed desserts.",
	"I don't eat processed bread.",
	"I don't eat high-calorie foods.",
	"I don't eat white bread.",
	'I am on a low-glycemic diet.',
	"I don't eat artificial flavors.",
	"I don't eat fruit snacks.",
	"I don't eat high-fiber foods.",
	'I have a celery allergy.',
	'I am on a low-fat diet.',
	"I don't eat high-fructose corn syrup.",
	"I don't eat frozen vegetables.",
	'I am on a low-glycemic diet.',
	"I don't eat processed soups.",
	"I don't eat processed cereals.",
	"I don't eat white bread.",
	"I don't eat high-sugar foods.",
	"I can't eat energy bars.",
	'I am on a low-sugar diet.',
	'I have a chocolate allergy.',
	"I don't eat frozen dinners.",
	"I don't eat canned fruits.",
	"I don't eat high-sugar foods.",
	'I am on a low-cholesterol diet.',
	'I have a barbecue sauce allergy.',
	"I don't eat high-calorie foods.",
	"I don't eat white flour.",
	"I don't eat artificial flavors.",
	'I am on a low-glycemic diet.',
	"I don't eat processed snacks.",
	"I don't eat high-fat foods.",
	"I don't eat high-sodium foods.",
	"I don't eat processed condiments.",
	'I am on a low-fat diet.',
	'I have a ketchup allergy.',
	"I don't eat high-cholesterol foods.",
	"I can't eat artificial sweeteners.",
	"I don't eat high-sugar foods.",
	'I am on a low-sugar diet.',
	'I have a white flour allergy.',
	"I don't eat processed desserts.",
	"I don't eat processed bread.",
	"I don't eat high-calorie foods.",
	'I am lactose intolerant.',
	"I can't eat gluten.",
	'I follow a vegetarian diet.',
	'I am allergic to nuts.',
	"I don't eat red meat.",
	'I am on a low-carb diet.',
	'I have a seafood allergy.',
	"I don't consume alcohol.",
	'I am vegan.',
	'I avoid dairy products.',
	"I can't have spicy food.",
	'I am diabetic.',
	'I have a sensitivity to soy.',
	'I am on a keto diet.',
	'I follow a halal diet.',
	'I am allergic to shellfish.',
	"I don't eat pork.",
	'I am pescatarian.',
	'I have Celiac disease.',
	'I am allergic to eggs.',
	'I have a gluten sensitivity.',
	'I follow a paleo diet.',
	"I don't eat processed foods.",
	'I am on a low-fat diet.',
	'I have a citrus allergy.',
	"I don't eat nightshade vegetables.",
	'I am allergic to dairy.',
	'I avoid high-sodium foods.',
	'I have a caffeine sensitivity.',
	"I don't eat fast food.",
	'I am on a high-protein diet.',
	'I follow a kosher diet.',
	'I have a fructose intolerance.',
	'I am allergic to wheat.',
	"I don't consume artificial sweeteners.",
	'I am on a low-sugar diet.',
	'I have a sulfite sensitivity.',
	"I don't eat raw foods.",
	'I am on a low-cholesterol diet.',
	'I follow a non-GMO diet.',
	'I have a mustard allergy.',
	"I don't eat spicy food.",
	'I am on a low-calorie diet.',
	'I have a sunflower seed allergy.',
	'I avoid high-mercury fish.',
	'I am on a low-sodium diet.',
	'I have a fig allergy.',
	"I don't eat high-oxalate foods.",
	'I am allergic to sesame.',
	'I avoid high-lectin foods.',
	'I have an apple allergy.',
	'I am on a low-caffeine diet.',
	'I follow a non-dairy diet.',
	'I have a wheat allergy.',
	"I don't eat high-histamine foods.",
	'I am on a low-yeast diet.',
	'I have a dill allergy.',
	'I avoid high-tyramine foods.',
	'I am allergic to yogurt.',
	"I don't eat high-sugar foods.",
	'I am on a low-fiber diet.',
	'I have a barley allergy.',
	'I avoid high-fodmap foods.',
	'I am on a low-residue diet.',
	'I have a blue cheese allergy.',
	"I don't eat high-glycemic index foods.",
	'I am allergic to lamb.',
	'I avoid high-oxalate foods.',
	'I am on a low-histamine diet.',
	'I have a Brazil nut allergy.',
	"I don't eat high-lectin foods.",
	'I am allergic to mayonnaise.',
	'I avoid high-tyramine foods.',
	'I am on a low-yeast diet.',
	'I have a bromelain allergy.',
	"I don't eat high-fodmap foods.",
	'I am allergic to mushrooms.',
	'I avoid high-sulfur foods.',
	'I am on a low-glycemic index diet.',
	'I have a buckwheat allergy.',
	"I don't eat high-ascorbic acid foods.",
	'I am allergic to oatmeal.',
	'I avoid high-fiber foods.',
	'I am on a high-residue diet.',
	'I have a carrot allergy.',
	"I don't eat high-histidine foods.",
	'I am allergic to peas.',
	'I avoid high-fructose foods.',
	'I am on a low-insoluble fiber diet.',
	'I have a cauliflower allergy.',
	"I don't eat high-tryptophan foods.",
	'I am allergic to watermelon.',
	'I avoid high-lactose foods.',
	'I am on a low-monosodium glutamate diet.',
	'I have a cherry allergy.',
	"I don't eat high-alcohol foods.",
	'I am allergic to honey.',
	'I avoid high-calcium foods.',
	'I am on a low-ethanol diet.',
	'I have a chocolate allergy.',
	"I don't eat high-glucose foods.",
	'I am allergic to coconut.',
	'I avoid high-starch foods.',
	'I am on a low-gluten diet.',
	'I have a corn allergy.',
	"I don't eat high-riboflavin foods.",
	'I am allergic to garlic.',
	'I avoid high-iron foods.',
	'I am on a low-lactose diet.',
	'I have a grape allergy.',
	"I don't eat high-lipid foods.",
	'I am allergic to green tea.',
	'I avoid high-manganese foods.',
	'I am on a low-linoleic acid diet.',
	'I have a kiwi allergy.',
	"I don't eat high-niacin foods.",
	'I am allergic to lettuce.',
	'I avoid high-nitrate foods.',
	'I am on a low-nitrite diet.',
	'I have a melon allergy.',
	"I don't eat high-histamine foods.",
	'I am allergic to mint.',
	'I avoid high-ascorbic acid foods.',
	'I am on a low-histidine diet.',
	'I have a mushroom allergy.',
	"I don't eat high-insoluble fiber foods.",
	'I am allergic to onions.',
	'I avoid high-tryptophan foods.',
	'I am on a low-alcohol diet.',
	'I have a peanut allergy.',
	"I don't eat high-calcium foods.",
	'I am allergic to peppers.',
	'I avoid high-ethanol foods.',
	'I am on a low-glucose diet.',
	'I have a pineapple allergy.',
	"I don't eat high-starch foods.",
	'I am allergic to prawns.',
	'I avoid high-riboflavin foods.',
	'I am on a low-riboflavin diet.',
	'I have a radish allergy.',
	"I don't eat high-iron foods.",
	'I am allergic to rice.',
	'I avoid high-lipid foods.',
	'I am on a low-niacin diet.',
	'I have a steak allergy.',
	"I don't eat high-manganese foods.",
	'I am allergic to squash.',
	'I avoid high-nitrate foods.',
	'I am on a low-nitrite diet.',
	'I have a sugar allergy.',
	"I don't eat high-histamine foods.",
	'I am allergic to sunflower seeds.',
	'I avoid high-ascorbic acid foods.',
	'I am on a low-histidine diet.',
	'I have a tomato allergy.',
	"I don't eat high-insoluble fiber foods.",
	'I am allergic to vanilla.',
	'I avoid high-tryptophan foods.',
	'I am on a low-alcohol diet.',
	'I have a wheat allergy.',
	"I don't eat high-calcium foods.",
	'I am allergic to yogurt.',
	'I avoid high-ethanol foods.',
	'I am on a low-glucose diet.',
	'I have a zucchini allergy.',
];

const extractor = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2');

const embeddings = await Promise.all(
	sentences.map((s) => extractor(s, { pooling: 'mean', normalize: true })),
);

const umap = new UMAP({
	nComponents: 3,
	minDist: 0.001,
	spread: 10,
	nNeighbors: 50,
});

const projections = await umap.fitAsync(embeddings);

console.log(JSON.stringify(projections.map((p, i) => [...p, sentences[i]])));
